filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /files/idoc_idoc.csv
  - type: log
    enabled: true
    paths:
      - /files/powerbi_link_activity.csv
  - type: log
    enabled: true
    paths:
      - /files/powerbi_requestor_activity.csv
  - type: log
    enabled: true
    paths:
      - /files/powerbi_statuses.csv

output.logstash:
  hosts: ["logstash:5044"]
